# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_earning',
            field=models.FloatField(default=0),
        ),
    ]
