# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='gamenum',
            new_name='game_number',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='maxtime',
            new_name='max_time',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='playernum',
            new_name='player_number',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='rivalnum',
            new_name='skill_group_number',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='skillgroupnum',
            new_name='training_number',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='trainingnum',
        ),
    ]
