# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0002_user_total_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='total_participants_number',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='contest_number',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='game_max_minutes',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='game_minutes_to_reveal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='game_number',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='player_number',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='training_number',
            field=models.IntegerField(default=6),
        ),
    ]
