# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0002_auto_20160509_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='skill_group_number',
            new_name='winning_threshold',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='skill',
            new_name='total_game_score',
        ),
        migrations.AddField(
            model_name='user',
            name='total_training_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergame',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
