# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0003_auto_20160509_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='max_time',
            new_name='game_max_time',
        ),
        migrations.AddField(
            model_name='experiment',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
