# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0005_auto_20160509_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='total_time',
            new_name='game_max_minutes',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='winning_threshold',
            new_name='total_minutes',
        ),
    ]
