# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0006_auto_20160509_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='game_max_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='total_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='waiting_for_game',
            field=models.BooleanField(default=0),
        ),
    ]
