# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0010_auto_20160511_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertraining',
            old_name='training',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
