# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0014_auto_20160516_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='complete_information',
        ),
        migrations.RemoveField(
            model_name='game',
            name='intermediate_information',
        ),
        migrations.RemoveField(
            model_name='game',
            name='no_information',
        ),
        migrations.AddField(
            model_name='user',
            name='complete_information',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='intermediate_information',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_information',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usergame',
            name='complete_information',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usergame',
            name='intermediate_information',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usergame',
            name='no_information',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
