# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0015_auto_20160516_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winning_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='winning_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
