# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0017_auto_20160520_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='optimal_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_0',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_1',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_10',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_11',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_2',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_3',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_4',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_5',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_6',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_7',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_8',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='optimal_9',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
