# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0018_auto_20160521_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='optimal_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='winning_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='winning_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_game_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_training_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usertraining',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
