# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0019_auto_20160522_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='for_contest',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
