# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0020_auto_20160606_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='difficulty_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gametype',
            name='for_training',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
