# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0022_auto_20160611_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievement',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='africanamerican',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='asian',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='caucasian',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='changeopinion',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='female',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='graduate',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hispanic',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='user',
            name='male',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='multiracial',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nativeamerican',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='notstudent',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otherethnicity',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AddField(
            model_name='user',
            name='participatedbefore',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='programyear',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='siblings',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='stickopinion',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='strategies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='undergraduate',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='white',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
