# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0023_auto_20160614_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.IntegerField(default=0)),
                ('seconds_to_reveal', models.IntegerField(default=0)),
                ('minutes_to_reveal', models.IntegerField(default=0)),
                ('no_information', models.BooleanField(default=0)),
                ('intermediate_information', models.BooleanField(default=0)),
                ('complete_information', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contestusergame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Contest')),
                ('usergame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usergame')),
            ],
        ),
        migrations.CreateModel(
            name='Contestusertraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Contest')),
                ('usertraining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining')),
            ],
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
