# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0026_auto_20160714_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='minutes_to_reveal',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='player_number',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='seconds_to_reveal',
        ),
        migrations.AddField(
            model_name='experiment',
            name='contest_earning',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='experiment',
            name='training_contest_earning',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='experiment',
            name='training_earning',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='contestusertraining',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
