# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0038_auto_20160810_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='initializing',
            new_name='group1_initializing',
        ),
        migrations.AddField(
            model_name='experiment',
            name='group2_initializing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='group3_initializing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='group4_initializing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='infeasibility_chance',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='experiment',
            name='total_training_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='total_training_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='infeasible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gametype',
            name='difficulty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='finished_training',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='started_training',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contestusertraining',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
