# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0040_auto_20161006_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='complete_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='group1_current_Contest_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='group2_current_Contest_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='group3_current_Contest_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='group4_current_Contest_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='intermediate_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='no_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contestusertraining',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
