# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0045_auto_20161030_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='opponentWon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergame',
            name='youWon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contestusertraining',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
