# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knapsack', '0049_auto_20161030_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userquitquesstion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_quit', models.TextField(blank=True, null=True)),
                ('is_feasible', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.User')),
            ],
        ),
        migrations.CreateModel(
            name='Userquiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_quit', models.TextField(blank=True, null=True)),
                ('is_feasible', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.User')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='quit_question_earning',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='experiment',
            name='quiz_question_earning',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='contestusertraining',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
        migrations.AlterField(
            model_name='usertrainingitem',
            name='usertraining',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knapsack.Usertraining'),
        ),
    ]
